In [1]:
import numpy as np
import pandas as pd
#import fiona 
import geopandas as gpd
#import math
#from netCDF4 import Dataset
import xarray as xa
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap

In [2]:
path = 'c:/Users/markstro/work1.1/weather/'
gdb_path = 'c:/Users/markstro/work1.1/GIS/GFv1.1_v2e.gdb'

#fns = [("2011", "2011_gm_climate_2020_03_02.nc"), ("2012", "2012_gm_climate_2020_03_03.nc"),
#       ("2013", "2013_gm_climate_2020_03_05.nc"), ("2014", "2014_gm_climate_2020_03_06.nc"),
#       ("2015", "2015_gm_climate_2020_03_08.nc"), ("2016", "2016_gm_climate_2020_03_09.nc"),
#       ("2017", "2017_gm_climate_2020_03_10.nc"), ("2018", "2018_gm_climate_2020_03_12.nc")]

fns = [("2015", "2015_gm_climate_2020_03_08.nc")]

param_path = "c:/Users/markstro/work1.1/paramdb_v1.1/paramdb_master/"

In [ ]:
# Read the weather data from the ncf files.

#prcp = xa.Dataset()
#tmax = xa.Dataset()
#hruid = xa.Dataset()
#time = xa.Dataset()

In [3]:
# Read the ncf weather file

ds = xa.open_dataset(path + "2015_gm_climate_2020_03_08.nc")

In [ ]:
# Continue to read the weather data from the ncf files.

#for fn in fns:
#    yr_str = fn[0]
#    ds = xa.open_dataset(path + fn[1])

#    tmax[yr_str] = ds["tmax"].load()
#    hruid[yr_str] = ds["hruid"].load()
#    prcp[yr_str] = ds["prcp"].load()
#    time[yr_str] = ds["time"].load()

In [4]:
# Continue to read the weather data from the ncf files.

jday = 183

foo = ds["tmax"].values
tmax_v = foo[jday-1, :]
hruid_v = ds["hruid"].values

# number of HRUs is 114958

print(tmax_v)
print(min(tmax_v), max(tmax_v))
print(hruid_v)
print(min(hruid_v), max(hruid_v))
print(len(tmax_v), len(hruid_v))

[31.889582 31.877855 31.808846 ... 26.97743  24.992785 21.564814]
0.0 46.399994
[76128 76148 76171 ... 64151 65634 18844]
0 109951
139807 139807


In [10]:
s = np.sort(hruid_v, axis=None)
s[:-1][s[1:] == s[:-1]]

array([     0,      0,      0, ..., 109951, 109951, 109951])

In [5]:
# Read the GDB with the georeferenced features, ie HRUs

nhru_v11 = gpd.read_file(gdb_path, layer='nhru_v11')

In [6]:
nhru_v11_v = nhru_v11['nhru_v11'].values
print(nhru_v11_v)
print(min(nhru_v11_v), max(nhru_v11_v))
print(len(nhru_v11_v))

[76127 76147 76170 ... 64150 65633 18843]
1 114958
114958


In [9]:
hruid_v1 = hruid_v -1

#plt.hist(hruid_v1)
#plt.show
count = 0
for ii in range(len(hruid_v1)):
    if hruid_v1[ii] < 0:
        count += 1
print(count, count + 114958 )

13492 128450


In [ ]:
tmax_mapped = np.empty(len(nhru_v11_v))
tmax_mapped[:] = np.NaN

for ii in range(nhru):
    tmax_mapped[ii] = tmax_v[hruid_v1[ii] - 1]

In [ ]:
#for fn in fns:
#    yr_str = fn[0]
#    print(prcp[yr_str])

In [ ]:
#for fn in fns:
#    yr_str = fn[0]
#    print(time[yr_str])

In [ ]:
nhru_v11['tmax'] = tmax_mapped

In [ ]:
nhru_v11.head

In [ ]:
coolwarm = cm.get_cmap('coolwarm', 12)
print(coolwarm)

In [ ]:
# plot the values


# plot all HRUs in white (background color)
f, ax = plt.subplots(1, figsize=(12, 12))
#nhru_v11.plot(color="white", ax=ax)

# df.dropna(thresh=2)

# plot the HRUs with valid temperature (non-nan) with their color ramp colors
nhru_v11.plot(column='tmax', cmap='coolwarm', ax=ax, legend=True)

In [ ]:
plt.plot(nhru_v11["tmax"])
plt.show()